`timescale 1ns/1ps
// instr_mem_rbt.v - instruction memory, 512 x 32, asynchronous read
//
//   The program is embedded in the RTL (rom_image.v, generated by programs/hex2rom.py), so synthesis
//   and simulation need no external file. Default image: programs/hex/line_follower.hex.
//
//   Simulation override: compile with -DSIM_PLUSARGS and run  vvp sim +hex=programs/hex/bench_mmio.hex
//   (used by the benchmark scripts; has no effect on synthesis).

module instr_mem_rbt #(parameter MEM_SIZE = 512, parameter HEX_FILE = "unused") (
    input  [31:0] instr_addr,
    output [31:0] instr
);

wire [31:0] rom_data;
rom_image u_rom (.addr(instr_addr[10:2]), .data(rom_data));

`ifdef SIM_PLUSARGS
reg [31:0] instr_ram [0:MEM_SIZE-1];
reg [8*256-1:0] fname;
reg override = 1'b0;
integer k;
initial begin
    if ($value$plusargs("hex=%s", fname)) begin
        for (k = 0; k < MEM_SIZE; k = k + 1) instr_ram[k] = 32'h00000013;
        $readmemh(fname, instr_ram);
        override = 1'b1;
    end
end
assign instr = override ? instr_ram[instr_addr[10:2]] : rom_data;
`else
assign instr = rom_data;
`endif

endmodule
