// rom_image.v - GENERATED FILE. DO NOT EDIT BY HAND.
// Generated by programs/hex2rom.py (run programs/build.sh to regenerate).
// Source: programs/hex/line_follower.hex

module rom_image (
    input  [8:0] addr,
    output reg [31:0] data
);

always @(*) begin
    case (addr)
        9'd0: data = 32'h40000437;
        9'd1: data = 32'h00100293;
        9'd2: data = 32'h00542623;
        9'd3: data = 32'h0000150b;
        9'd4: data = 32'hffdff06f;
        default: data = 32'h00000013;
    endcase
end

endmodule
