#!/usr/bin/env python3
"""hex2rom.py - convert a .hex program (one 32-bit word per line) into a Verilog-2001 ROM module.

Usage: python3 programs/hex2rom.py <input.hex> <output.v>

ROM: 512 words x 32 bit, 9-bit word address. Unlisted addresses return 32'h00000013 (NOP).
"""

import os
import sys

MEM_WORDS = 512
NOP = 0x00000013


def die(msg):
    sys.stderr.write("hex2rom.py: ERROR: %s\n" % msg)
    sys.exit(1)


def main():
    if len(sys.argv) != 3:
        die("usage: python3 programs/hex2rom.py <input.hex> <output.v>")

    hex_file, out_file = sys.argv[1], sys.argv[2]

    words = []
    try:
        with open(hex_file, "r") as f:
            for lineno, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue
                try:
                    value = int(line, 16)
                except ValueError:
                    die("%s:%d: invalid hex word '%s'" % (hex_file, lineno, line))
                if value < 0 or value > 0xFFFFFFFF:
                    die("%s:%d: value does not fit in 32 bits" % (hex_file, lineno))
                words.append(value)
    except IOError as e:
        die("cannot read %s: %s" % (hex_file, e))

    if len(words) > MEM_WORDS:
        die("%s has %d words, but the ROM holds only %d words"
            % (hex_file, len(words), MEM_WORDS))

    with open(out_file, "w") as f:
        f.write("// rom_image.v - GENERATED FILE. DO NOT EDIT BY HAND.\n")
        f.write("// Generated by programs/hex2rom.py (run programs/build.sh to regenerate).\n")
        f.write("// Source: programs/hex/%s\n\n" % os.path.basename(hex_file))
        f.write("module rom_image (\n")
        f.write("    input  [8:0] addr,\n")
        f.write("    output reg [31:0] data\n")
        f.write(");\n\n")
        f.write("always @(*) begin\n")
        f.write("    case (addr)\n")
        for i, word in enumerate(words):
            f.write("        9'd%d: data = 32'h%08x;\n" % (i, word))
        f.write("        default: data = 32'h%08x;\n" % NOP)
        f.write("    endcase\n")
        f.write("end\n\n")
        f.write("endmodule\n")


if __name__ == "__main__":
    main()
